version: '3.9'
services:
  sistema_concrete_java:
    container_name: sistema_concrete_java
    build: 
      dockerfile: /Users/ana.paula.m.amarante/Documents/Treinamento Gama DevOps//validadorCPF/Dockerfile
      context: /Users/ana.paula.m.amarante/Documents/Treinamento Gama DevOps//validadorCPF/.
    image: concreteanaamarante/validador-cpf-java-local
    ports: 
      - "3001:8080"
  sistema_concrete_dotnet:
    container_name: sistema_concrete_dotnet
    image: concreteanaamarante/validador-cpf-dotnet
    ports: 
      - "3002:80"