version: '3.9'
services:
  sistema_concrete_java:
    container_name: sistema_concrete_java
    image: concreteanaamarante/validador-cpf-java
    ports: 
      - "3001:8080"
  sistema_concrete_dotnet:
    container_name: sistema_concrete_dotnet
    image: concreteanaamarante/validador-cpf-dotnet
    ports: 
      - "3002:80"